### PR TITLE
Changed path of cfn-init&cfn-signal to /opt/aws/bin

### PR DESCRIPTION
**Pull request by MishalYadav**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by andrew-glenn — DISMISSED** [review]

**Comment by tlindsay42** [comment]
Hi @MishalYadav! When you have a chance, I created pull request https://github.com/MishalYadav/quickstart-boomi-molecule/pull/1 to add a .metadata file to your pull request. This file is required for our new CI before we can run an end-to-end test on this pull request. Would you merge it in when you have a chance, please?

**Comment by tlindsay42** [comment]
Never mind. Wasn't thinking and went about that the hard way. Addressing in #46.

**Pull request closed without merging**
